### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: XXX.a3m

### ISSUE THREAD

**Issue by NikolaTeslein** [wells-wood-research/alphafold2-multiprocessing#2]
Hello! I am encountering a problem as below, 
——————————————————————————————————————————————————
python run_fold.py --workers 1 --num_models 1 --input_file ../Input_Seq/2pgf.fasta
Starting 2PGF_1|ChainA|adenosine_deaminase|Plasmodium_vivax_(5855)
sh: 1: ./msa2.bsh: Permission denied
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/teslein/miniconda3/envs/fold/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/teslein/miniconda3/envs/fold/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "run_fold.py", line 114, in run_model
    a3m_lines = "".join(open(f"{jobname}.a3m", "r").readlines())
FileNotFoundError: [Errno 2] No such file or directory: '2PGF_1ChainAadenosine_deaminasePlasmodium_vivax_5855.a3m'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_fold.py", line 304, in <module>
    main(params)
  File "run_fold.py", line 287, in main
    list(predicted_sequence_dict.keys()),
  File "/home/teslein/miniconda3/envs/fold/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/teslein/miniconda3/envs/fold/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
**FileNotFoundError: [Errno 2] No such file or directory:** '2PGF_1ChainAadenosine_deaminasePlasmodium_vivax_5855.a3m'
————————————————————————————————————————————————
Hope for a resolution !

**Comment by DrLeucine** [comment]
Hi there, could you try to place the "2pgf.fasta" file in the same folder as this repo?

Essentially run this:

```
python run_fold.py --workers 1 --num_models 1 --input_file 2pgf.fasta
```


Apologies for the delay, I'm currently working on my Master's dissertation and have not seen this earlier.

**Comment by DrLeucine** [comment]
Also, I see a couple of permission denied errors. Could you try to run:

```
chmod u+x dependency_install.bsh
chmod u+x msa2.bsh
```
